Add loading state for successfull otp read
GoHappy-Club/Go-Happy-Client pull request #60
Opened 2024-09-12 11:32 UTC by mehul-gohappy

2024-09-13 05:16 UTC, Rakshit1411 requested changes

2024-09-13 05:16 UTC, Rakshit1411 commented on screens/loginScreen/LoginScreen.js
> +          // firebase.auth().onAuthStateChanged((user) => {
why ?

2024-09-14 03:12 UTC, mehul-gohappy commented on screens/loginScreen/LoginScreen.js
> +          // firebase.auth().onAuthStateChanged((user) => {
this onAuthStateChanged function gets triggered automatically when an OTP is recieved from firebase on the device, and if we trigger the _backend_signin manually, both of these will get triggered and one of them will produce the invalid credentials error
this function is also calling the backend_signin method inside

2024-09-14 04:03 UTC, Rakshit1411 commented on screens/loginScreen/LoginScreen.js
> +          // firebase.auth().onAuthStateChanged((user) => {
But this was not the intended task, right ?

2024-09-14 04:03 UTC, Rakshit1411 commented on screens/loginScreen/LoginScreen.js
> +          // firebase.auth().onAuthStateChanged((user) => {
This PR should only contain [Add loading state for successfull otp read]

2024-09-14 13:21 UTC, Rakshit1411 approved these changes

2024-09-14 13:21 UTC, merged