fix whatsapp link bug
GoHappy-Club/Go-Happy-Client pull request #64
Opened 2024-09-16 08:10 UTC by mehul-gohappy

remaining fixxess

2024-09-17 01:18 UTC, Rakshit1411 requested changes

2024-09-17 01:18 UTC, Rakshit1411 commented on components/Profile.js
> +          console.log(properties);
remove console.log

2024-09-17 01:18 UTC, Rakshit1411 commented on screens/homeScreen/HomeScreen.js
> +              <WhatsAppFAB/>
what is the diff between these 2 ?

2024-09-17 01:18 UTC, Rakshit1411 commented on screens/overview/OverviewScreen.js
> +            this.props.profile.age > 50 && <WhatsAppFAB />
what is the diff between 2 ?

2024-09-17 02:04 UTC, mehul-gohappy commented on screens/homeScreen/HomeScreen.js
> +              <WhatsAppFAB/>
we are fetching the whatsapp link in the WhatsAppFAB component when it mounts so we don't need to pass any url explicitly

2024-09-17 02:04 UTC, mehul-gohappy commented on screens/overview/OverviewScreen.js
> +            this.props.profile.age > 50 && <WhatsAppFAB />
we are fetching the whatsapp link in the WhatsAppFAB component when it mounts so we don't need to pass any url explicitly

2024-09-19 01:42 UTC, Rakshit1411 approved these changes

2024-09-19 01:42 UTC, merged