Change share message in sessions
GoHappy-Club/Go-Happy-Client pull request #68
Opened 2024-09-27 04:11 UTC by mehul-gohappy

2024-09-27 11:53 UTC, Rakshit1411 requested changes

2024-09-27 11:53 UTC, Rakshit1411 commented on components/HomeDashboard.js
> +      itemClicked: null,
what is this used for ?

2024-09-27 17:10 UTC, mehul-gohappy commented on components/HomeDashboard.js
> +      itemClicked: null,
to provide the event details to send in the share message

2024-10-01 02:38 UTC, Rakshit1411 approved these changes

2024-10-01 02:38 UTC, merged